DECLARE
   counts INTEGER;
BEGIN
	for v_rec in (
		SELECT C1.CUSTOMERID, COUNT(*) as counts
        FROM CUSTOMER C1, CUSTOMER C2 WHERE C1.CUSTOMERID != C2.CUSTOMERID AND SDO_RELATE(C1.ROADTOEMPLOYEE, C2.ROADTOEMPLOYEE, 'mask=ANYINTERACT querytype=JOIN') = 'TRUE' AND C1.CUSTOMERID < 100 AND C2.CUSTOMERID < 100
        GROUP BY C1.CUSTOMERID
        ORDER BY C1.CUSTOMERID, COUNT(*) DESC  
	) 
	loop
		counts := v_rec.counts;
	end loop;
END;

