DELETE FROM TABLE INVOICELINE
WHERE INVOICELINE.INVOICELINEID IN 
(
SELECT INVOICELINE.INVOICELINEID FROM INVOICELINE
INNER JOIN TRACK
ON TRACK.TRACKID = INVOICELINE.TRACKID
INNER JOIN (SELECT GENREID FROM GENRE WHERE GENREID = 3) DT0
ON TRACK.GENREID = DT0.GENREID
INNER JOIN (
    SELECT INVOICE.INVOICEID, INVOICE.CUSTOMERID FROM INVOICE
    INNER JOIN CUSTOMER
    ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
    WHERE INVOICE.BILLINGCITY = CUSTOMER.CITY
) DT1
ON INVOICELINE.INVOICEID = DT1.INVOICEID
INNER JOIN (
    SELECT INVOICE.CUSTOMERID FROM INVOICE
    INNER JOIN CUSTOMER
    ON CUSTOMER.CUSTOMERID = INVOICE.INVOICEID
    GROUP BY INVOICE.CUSTOMERID
    HAVING SUM(INVOICE.TOTAL) > 6
) DT2
ON DT1.CUSTOMERID = DT2.CUSTOMERID
)