--SELECT *
--FROM TRACK 
--INNER JOIN ALBUM
--ON TRACK.ALBUMID = ALBUM.ALBUMID
--INNER JOIN ARTIST
--ON ALBUM.ARTISTID = ARTIST.ARTISTID
--INNER JOIN PLAYLISTTRACK
--ON TRACK.TRACKID = PLAYLISTTRACK.TRACKID
--GROUP BY 


SELECT ARTIST.ARTISTID, SUM(DT."InPlaylists")
FROM TRACK 
INNER JOIN

(SELECT TRACKID, COUNT(*) AS "InPlaylists" FROM PLAYLISTTRACK
GROUP BY TRACKID
ORDER BY 2 DESC) DT
ON TRACK.TRACKID = DT.TRACKID

INNER JOIN ALBUM
ON TRACK.ALBUMID = ALBUM.ALBUMID
INNER JOIN ARTIST
ON ALBUM.ARTISTID = ARTIST.ARTISTID

GROUP BY ARTIST.ARTISTID
ORDER BY 2 DESC