UPDATE customer
SET SUPPORTREPID = 1
WHERE CUSTOMERID IN 
(SELECT CUSTOMER.CUSTOMERID
FROM GENRE
INNER JOIN TRACK
ON GENRE.GENREID = TRACK.GENREID
INNER JOIN INVOICELINE
ON INVOICELINE.TRACKID = TRACK.TRACKID
INNER JOIN INVOICE
ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
INNER JOIN CUSTOMER
ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
WHERE GENRE.GENREID = 3 
GROUP BY CUSTOMER.CUSTOMERID
HAVING SUM(INVOICELINE.QUANTITY * INVOICELINE.UNITPRICE) > 3)