SELECT ARTIST.ARTISTID, AVG(MILLISECONDS) as AverageSongLength FROM TRACK
INNER JOIN MEDIATYPE
ON TRACK.MEDIATYPEID = MEDIATYPE.MEDIATYPEID
INNER JOIN ALBUM
ON ALBUM.ALBUMID = TRACK.TRACKID
INNER JOIN ARTIST
ON ARTIST.ARTISTID = ALBUM.ARTISTID
WHERE MEDIATYPE.NAME = 'MPEG audio file'
GROUP BY ARTIST.ARTISTID
HAVING AVG(TRACK.MILLISECONDS) > 60000
ORDER BY 2 DESC