DECLARE
   artistid INTEGER;
   avgsonglen INTEGER;
BEGIN
	for v_rec in (
		SELECT ARTIST.ARTISTID, AVG(MILLISECONDS) as AverageSongLength FROM TRACK
		INNER JOIN MEDIATYPE
		ON TRACK.MEDIATYPEID = MEDIATYPE.MEDIATYPEID
		INNER JOIN ALBUM
		ON ALBUM.ALBUMID = TRACK.TRACKID
		INNER JOIN ARTIST
		ON ARTIST.ARTISTID = ALBUM.ARTISTID
		WHERE MEDIATYPE.NAME = 'MPEG audio file'
		GROUP BY ARTIST.ARTISTID
		HAVING AVG(TRACK.MILLISECONDS) > 60000
		ORDER BY 2 DESC
	) 
	loop
		artistid := v_rec.ARTISTID;
		avgsonglen := v_rec.AverageSongLength;
	end loop;
END;
