UPDATE customer
SET EMAIL = '**********'
WHERE CUSTOMERID IN 
(
SELECT CUSTOMER.CUSTOMERID
FROM GENRE
INNER JOIN TRACK
ON GENRE.GENREID = TRACK.GENREID
INNER JOIN INVOICELINE
ON INVOICELINE.TRACKID = TRACK.TRACKID
INNER JOIN INVOICE
ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
INNER JOIN CUSTOMER
ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
INNER JOIN MEDIATYPE
ON MEDIATYPE.MEDIATYPEID = TRACK.MEDIATYPEID
WHERE GENRE.GENREID IN
(
    SELECT GENREID FROM GENRE
    WHERE GENRE.NAME LIKE '%Rock%'
)
AND TRACK.MEDIATYPEID = 1
GROUP BY CUSTOMER.CUSTOMERID
HAVING COUNT(INVOICELINE.INVOICELINEID) > 7
)