insert into PLAYLISTTRACK (PLAYLISTID, TRACKID) 
(
    SELECT 2, TRACKID FROM
(
    SELECT TRACK.TRACKID FROM TRACK
    INNER JOIN INVOICELINE
    ON TRACK.TRACKID = INVOICELINE.TRACKID
    GROUP BY TRACK.TRACKID
    ORDER BY COUNT(INVOICELINE.INVOICELINEID) DESC
)
WHERE ROWNUM <= 2
)