DECLARE
   artistid INTEGER;
   inplaylists INTEGER;
BEGIN
	for v_rec in (
		SELECT ARTIST.ARTISTID, SUM(DT."InPlaylists") as INPLAYLISTS1
		FROM TRACK 
		INNER JOIN
		(SELECT TRACKID, COUNT(*) AS "InPlaylists" FROM PLAYLISTTRACK
		GROUP BY TRACKID
		ORDER BY 2 DESC) DT
		ON TRACK.TRACKID = DT.TRACKID
		INNER JOIN ALBUM
		ON TRACK.ALBUMID = ALBUM.ALBUMID
		INNER JOIN ARTIST
		ON ALBUM.ARTISTID = ARTIST.ARTISTID
		GROUP BY ARTIST.ARTISTID
		ORDER BY 2 DESC
	) 
	loop
		artistid := v_rec.ARTISTID;
		inplaylists := v_rec.INPLAYLISTS1;
	end loop;
END;
