DELETE FROM EMPLOYEE WHERE EMPLOYEEID IN
(
	SELECT UNIQUE(emp.EMPLOYEEID)
    FROM EMPLOYEE emp
    INNER JOIN (SELECT c.CUSTOMERID, c.SUPPORTREPID
                        FROM (SELECT * FROM CUSTOMER WHERE COUNTRY = 'USA') c
                        LEFT OUTER JOIN (SELECT * FROM INVOICE WHERE INVOICEDATE  > DATE '2013-09-01') i on i.CUSTOMERID = c.CUSTOMERID
                        GROUP BY c.CUSTOMERID, c.SUPPORTREPID
                        HAVING COUNT(i.INVOICEID) = 0) customer ON customer.SUPPORTREPID = emp.EMPLOYEEID
    WHERE emp.BIRTHDATE < DATE '1950-01-01'
);