DELETE FROM EMPLOYEE WHERE EMPLOYEEID IN
(
	SELECT emp.EMPLOYEEID
	FROM EMPLOYEE emp
	LEFT OUTER JOIN (SELECT c.CUSTOMERID, c.SUPPORTREPID
						FROM (SELECT * FROM CUSTOMER WHERE COUNTRY = 'USA') c
						LEFT OUTER JOIN (SELECT * FROM INVOICE WHERE INVOICEDATE  > DATE '2013-09-01') i on i.CUSTOMERID = c.CUSTOMERID
						GROUP BY c.CUSTOMERID, c.SUPPORTREPID
						HAVING COUNT(i.INVOICEID) = 0) customer ON customer.SUPPORTREPID = emp.EMPLOYEEID
	GROUP BY emp.EMPLOYEEID
	HAVING COUNT(customer.CUSTOMERID) = 0
);