Update TRACK SET UNITPRICE = 2 WHERE TRACKID = 1

INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, CITY)
    SELECT 9, CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, 'Helpdesk warrior', CUSTOMER.CITY FROM CUSTOMER
    INNER JOIN INVOICE
    ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
    INNER JOIN INVOICELINE
    ON INVOICELINE.INVOICEID = INVOICE.INVOICEID
    WHERE 1 = INVOICELINE.TRACKID AND ROWNUM = 1;