INSERT INTO Track (TrackId, Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice)
VALUES (10000000, 'New Song', 237, 1, 1, 'Dylan, Bob', 264568, 8623572, 0.99);

INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE, CITY)
    SELECT 9, CUSTOMER.LASTNAME, CUSTOMER.FIRSTNAME, 'Helpdesk warrior', CUSTOMER.CITY FROM CUSTOMER
    INNER JOIN INVOICE
    ON INVOICE.CUSTOMERID = CUSTOMER.CUSTOMERID
    INNER JOIN INVOICELINE
    ON INVOICELINE.INVOICEID = INVOICE.INVOICEID
    WHERE 1 = INVOICELINE.TRACKID AND ROWNUM = 1;