INSERT INTO INVOICELINE (INVOICELINEID, INVOICEID, TRACKID, UNITPRICE, QUANTITY)
SELECT 300000 + INVOICE.INVOICEID, INVOICE.INVOICEID, 1, 0, 1 FROM INVOICE
INNER JOIN INVOICELINE
ON INVOICE.INVOICEID = INVOICELINE.INVOICEID
INNER JOIN TRACK
ON TRACK.TRACKID = INVOICELINE.TRACKID
INNER JOIN GENRE
ON TRACK.GENREID = GENRE.GENREID
WHERE (GENRE.NAME = 'Rock' OR GENRE.NAME = 'Jazz' OR GENRE.NAME = 'Blues') AND INVOICE.INVOICEID < 101
GROUP BY INVOICE.INVOICEID
ORDER BY INVOICE.INVOICEID ASC