-- Dodanie do każdej playlisty zawierającej utwór Lord of Light remixu tego utworu.
INSERT INTO TRACK VALUES (122005, 'Lord of Light - Remix', 94, 2, 1, null, 444614, 7393698, 0.99);

INSERT INTO PLAYLISTTRACK (PLAYLISTID, TRACKID)
SELECT PLAYLISTTRACK.PLAYLISTID, 122005 FROM PLAYLISTTRACK
INNER JOIN TRACK
ON TRACK.TRACKID = PLAYLISTTRACK.TRACKID
WHERE TRACK.NAME = 'Lord of Light';