DELETE FROM CUSTOMER WHERE CUSTOMERID IN
(
	SELECT customer.CUSTOMERID
	FROM (SELECT * FROM CUSTOMER WHERE COUNTRY = 'USA') customer
	LEFT OUTER JOIN (SELECT * FROM INVOICE WHERE INVOICEDATE  > DATE '2012-08-01') i on i.CUSTOMERID = customer.CUSTOMERID
	GROUP BY customer.CUSTOMERID
	HAVING COUNT(i.INVOICEID) = 0
);