UPDATE INVOICELINE SET UNITPRICE = 5.99, QUANTITY = 4
WHERE INVOICELINEID = 4340;

UPDATE INVOICE i
SET i.TOTAL = i.Total - (SELECT UNITPRICE * QUANTITY FROM INVOICELINE WHERE INVOICELINEID = 4340) + (5.99 * 4)
WHERE i.INVOICEID = 397;