-- FIRST XMLs
select i.INVOICEID, il.INVOICELINEID, REPLACE(il.UNITPRICE, ',', '.') as INVOICELINE_UNITPRICE, il.QUANTITY, t.TRACKID, t.NAME as TRACK, mt.NAME as MEDIATYPE, g.NAME as GENRE, t.COMPOSER, t.MILLISECONDS, t.BYTES, REPLACE(t.UNITPRICE, ',', '.') as TRACK_UNITPRICE from INVOICE i
inner join INVOICELINE il on il.INVOICEID = i.INVOICEID
inner join TRACK t on il.TRACKID = t.TRACKID
inner join GENRE g on t.GENREID = g.GENREID
inner join MEDIATYPE mt on t.MEDIATYPEID = mt.MEDIATYPEID;

-- SECOND XMLs
select p.PLAYLISTID, i.INVOICEID, to_char(i.INVOICEDATE,'DD/MM/YYYY') as INVOICEDATE, t.TRACKID, t.NAME as TRACK, g.NAME as GENRE, t.COMPOSER, t.MILLISECONDS
from INVOICE i
inner join INVOICELINE il on il.INVOICEID = i.INVOICEID
inner join TRACK t on il.TRACKID = t.TRACKID
inner join PLAYLISTTRACK pt on t.TRACKID = pt.TRACKID
inner join PLAYLIST p on pt.PLAYLISTID = p.PLAYLISTID
inner join GENRE g on t.GENREID = g.GENREID;

-- THIRD XMLs
select art.ARTISTID, alb.ALBUMID, alb.TITLE, tr.TRACKID, tr.NAME, tr.COMPOSER, tr.MILLISECONDS, tr.BYTES, REPLACE(tr.UNITPRICE, ',', '.') as UNITPRICE
from ARTIST art
inner join ALBUM alb on art.ARTISTID = alb.ARTISTID
inner join TRACK tr on  alb.ALBUMID = tr.ALBUMID;

